### ISSUE TITLE
"An error has occurred"

### ISSUE THREAD

**Issue by CrumplesHQ** [Solar-Tweaks/Solar-Tweaks#1074]
Having the same issue as this post on Mac.

Check Natives Error: TypeError: Cannot read property 'artifacts' of undefined
    at Jt (app://./js/app.1824f5fe.js:1:46400)
    at async Bt (app://./js/app.1824f5fe.js:1:52705)
    at async Proxy.launchGame (app://./js/app.1824f5fe.js:1:54488)

 Tried the suggested fix from @HypedDomi to no avail. Any other suggestions on how to fix this?

**MacOS:**
Open up terminal, and run `rm -rf ~/Library/Application Support/solartweaks`

Then you can relaunch Solar Tweaks, and it should resolve your issues.

_Originally posted by @HypedDomi in https://github.com/Solar-Tweaks/Solar-Tweaks/issues/1047#issuecomment-1500238679_

**Comment by CrumplesHQ** [comment]
Edit: I used the application "Find Any File" to search for folders named "solartweaks" and found one that was being modified each time I tried to launch. I manually deleted it myself and then restarted Solar Tweaks which fixed everything.
