### ISSUE TITLE
doesnt launch 

### ISSUE THREAD

**Issue by JIMF12** [Solar-Tweaks/Solar-Tweaks#229]
starts normally but crashes error:Couldn't download manifest: https://launchermeta.mojang.com/mc/game/version_manifest.json
Exception in thread "main" java.lang.RuntimeException: Failed to preload patched classes
        at com.moonsworth.lunar.patcher.LunarMain.<init>(Unknown Source)
        at com.moonsworth.lunar.patcher.LunarMain.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: Failed to read class: net.minecraft.v1_18.eheeppsahsspsppasheapppae
        at WWWWWNNNNWMWNNNNWNNNNMMWW.findClass(Unknown Source)
        at WWWWWNNNNWMWNNNNWNNNNMMWW.WWWWWNNNNWMWWWMWWMMMWMMWM(Unknown Source)
        ... 2 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.v1_18.eheeppsahsspsppasheapppae
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more

[process exited with code 1 (0x00000001)]

**Comment by 770grappenmaker** [comment]
This will only happen if your current 1.18 isnt correctly working, first try relaunching in the official lunar client launcher in 1.18.1
