### ISSUE TITLE
Solar Tweaks don't start.

### ISSUE THREAD

**Issue by Authentified** [Solar-Tweaks/Solar-Tweaks#6]
Sup, I have a problem with Solar Tweaks.

Indeed, at the end of its launch. This one remains blocked at the launching of the Java virtual machine. I have checked the Skip Checks then restarted the launcher, restarted my computer, uninstalled then restarted my pc then reinstalled Solar Tweaks, updated my OpenJDK or basic Java. This problem is persistent.

Could you help me? 

Thanks in advance, and have a nice day/evening. 
![image](https://user-images.githubusercontent.com/104450419/165342849-2b42241a-461f-4a53-b875-ea92ac84f4ea.png)

**Comment by 770grappenmaker** [comment]
Try scrolling down and set the correct jdk, or use the jre downloader if it doesn't work out.

**Comment by 770grappenmaker** [comment]
Though the fact that it cannot find the jre is a bug.

**Comment by Authentified** [comment]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 26/04/2022 18:31
Description: Initializing game

java.lang.NoClassDefFoundError: optifine/Utils
	at net.optifine.Config.checkDisplayMode(Config.java:3056)
	at net.optifine.Config.initDisplay(Config.java:210)
	at net.minecraft.v1_7.phapsespeaphehsehaaeshash.eeeepaphshepppspeephseeph(OpenGlHelper.java:82)
	at net.minecraft.v1_7.ashahspappepahashshehshhe.eaehhpheheepeaepeasshpsse(SourceFile:344)
	at net.minecraft.v1_7.ashahspappepahashshehshhe.sphhsaeeaspppaahehehhspas(SourceFile:713)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.moonsworth.lunar.patcher.LunarMain.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: Failed to read class: optifine.Utils
	at WWWWWNNNNWMWNNNNWNNNNMMWW.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 11 more
Caused by: java.lang.ClassNotFoundException: optifine.Utils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.optifine.Config.checkDisplayMode(Config.java:3056)
	at net.optifine.Config.initDisplay(Config.java:210)
	at net.minecraft.v1_7.phapsespeaphehsehaaeshash.eeeepaphshepppspeephseeph(OpenGlHelper.java:82)
	at net.minecraft.v1_7.ashahspappepahashshehshhe.eaehhpheheepeaepeasshpsse(SourceFile:344)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.v1_7.ashahspappepahashshehshhe.sphhsaeeaspppaahehehhspas(SourceFile:713)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.moonsworth.lunar.patcher.LunarMain.main(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.2, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 3111608496 bytes (2967 MB) / 3221225472 bytes (3072 MB) up to 4194304000 bytes (4000 MB)
	JVM Flags: 10 total; -Xms3G -Xmx3G -Xmn1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xmx4000m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.7
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1650 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 512.15, NVIDIA Corporation
	GL Caps: 
	Is Modded: Definitely; Client brand changed to 'Lunar Client c888646/SolarTweaks v1.6'
	Type: Client (map_client.txt)
	Resource Packs: [Autoclicker.zip, !    §3§o§lVape §2§o§lPack §8[§fv1§8].zip]
	Current Language: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.v1_7.eahhepapaseapsphpehesseae.phsphsaaahehsephsesasaaep()" because the return value of "net.minecraft.v1_7.ashahspappepahashshehshhe.shashppaphseesshaeespheeh(net.minecraft.v1_7.ashahspappepahashshehshhe)" is null
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 11
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 512.15
	OpenGlRenderer: NVIDIA GeForce GTX 1650 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
	
	Here is the crash report

**Comment by dtomvan** [comment]
![image](https://user-images.githubusercontent.com/51440893/165356601-45fa6cd4-2149-4c78-8f33-6705e3618875.png)

**Comment by Authentified** [comment]
Yeah, so I started 1.8.9 and this is working! Ty!

**Comment by 770grappenmaker** [comment]
A new upcoming version (v4.0.1) fixes it so that 1.7 also works. @Authentified
