### ISSUE TITLE
[1.7] Crashing on Launch

### ISSUE THREAD

**Issue by he3als** [Solar-Tweaks/Solar-Tweaks#889]
**Describe the bug**
With the latest version of Solar Tweaks and Solar Patcher, 1.7 does not launch and crashes on startup.
Other versions like 1.8 work.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Launcher Version: 4.3.1
 - Engine Version: Latest as of 24/02/23

**Additional context**
```
Exception in thread "Client thread" java.lang.IllegalStateException: Failed to boot Minecraft
        at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.optifine.Reflector
        at Genesis//net.minecraft.crash.CrashReport.populateEnvironment(CrashReport.java:163)
        at Genesis//net.minecraft.crash.CrashReport.<init>(CrashReport.java:55)
        at Genesis//net.minecraft.crash.CrashReport.makeCrashReport(CrashReport.java:442)
        at Genesis//net.minecraft.client.Minecraft.run(SourceFile:715)
        at Genesis//net.minecraft.client.main.Main.main(Unknown Source)
        ... 3 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.LinkageError: loader 'Genesis' @4cfbaf4 attempted duplicate abstract class definition for net.minecraft.client.renderer.entity.RendererLivingEntity. (net.minecraft.client.renderer.entity.RendererLivingEntity is in unnamed module of loader 'Genesis' @4cfbaf4, parent loader 'app') [in thread "Client thread"]
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
        at com.moonsworth.lunar.genesis.RHOHRRIRHCCOOOIRCHIOHRROH.findClass(Unknown Source)
        at com.moonsworth.lunar.genesis.RHOHRRIRHCCOOOIRCHIOHRROH.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at Genesis//net.optifine.Reflector.<clinit>(Reflector.java:149)
        at Genesis//net.optifine.ReflectorForge.putLaunchBlackboard(ReflectorForge.java:50)
        at Genesis//net.optifine.Config.initGameSettings(Config.java:194)
        at Genesis//net.minecraft.client.settings.GameSettings.<init>(GameSettings.java:389)
        at Genesis//net.minecraft.client.Minecraft.startGame(SourceFile:286)
        at Genesis//net.minecraft.client.Minecraft.run(SourceFile:713)
        ... 4 more
```

**Comment by HypedDomi** [comment]
Disable Cracked Accounts until we fix it

**Comment by he3als** [comment]
Cracked accounts is disabled

**Comment by HypedDomi** [comment]
Then Send your logs please
1. Open SolarTweaks
2. Go to the About Tab
3. Click `Open ST directory`
4. Send the logs folder

**Comment by he3als** [comment]
There's no logs written, but I ran the launch command in Command Prompt. As a note, changing the JDK/JRE or JVM arguments does not fix this. I'll also post my Solar Engine settings. I have tried deleting the offline folder and other Lunar folders, launching via Lunar Client first, etc...
[log.txt](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10822353/log.txt)

[solarengine.txt](https://github.com/Solar-Tweaks/Solar-Tweaks/files/10822396/solarengine.txt)

**Comment by he3als** [comment]
As a note, the testing build in the pins of the community support channel in the Solar Socket Discord does not fix this issue for me.

**Comment by he3als** [comment]
Solar Engine 2.0.9 fixes this issue, thank you. https://github.com/Solar-Tweaks/Solar-Engine/releases/tag/v2.0.9
